name: Deploy dist folder to Azure Web App - appservicefront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the dist folder
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABC0244372044B82A79C2EB26654EB60 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_907DC1A83B56457FB0E346A3754DCC0A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F9C9EF5D53904E8DABBF8F1B06993C12 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appservicefront'
          slot-name: 'Production'
          package: release.zip
